/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import controller.ProjectController;
import java.sql.Connection;
import java.util.List;
import model.Project;
import utility.DatabaseConnection;

public class App {
    

    public static void main(String[] args) {
        
        ProjectController projectController = new ProjectController();
                
        Project projeto = new Project();
        
//        projeto.setName("Lojas MF");
//        projeto.setDescription("Site para venda de roupas masculinas e femininas");
//        
//        projectController.saveProject(projeto);
        projeto.setId(1);
        projeto.setName("Loja MF");
        projeto.setDescription("Site para venda de roupas masculinas e femininas");
        projectController.updateProject(projeto);
        
        List<Project> projetos = projectController.getAll();
        System.out.println("Total de projetos: " + projetos.size());
                
                
        
    }
}
